apiVersion: v1
kind: Service
metadata: 
  name: k8s-python-hello-world
spec:
  selector: 
    app.kubernetes.io/name: k8s-python-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  type: NodePort